web/main/__init__.py
from flask import Blueprint

bp = Blueprint("main", __name__, template_folder="templates")

from . import routes

web/main/routes.py
import glob
import json

import os
import re
import uuid
from zoneinfo import ZoneInfo

import dateutil.parser as parser
import pandas as pd
import redis
import requests
from rq.job import Job
from rq.exceptions import NoSuchJobError
from redis.connection import ConnectionError
from redis.exceptions import RedisError

from sqlalchemy import func

from flask import (
    render_template,
    current_app,
    request,
    flash,
    redirect,
    url_for,
    send_file,
    Response,
    send_from_directory,
    abort,
)
from werkzeug.utils import secure_filename

from bht.errors import BhtCsvError
from bht.pipeline import PipeStep
from tools import StepLighter
from . import bp
from web import db
from web.models import Paper, Mission, HpEvent, BhtFileType, stream_to_db, istexjson_to_db
from bht.catalog_tools import rows_to_catstring
from web.bht_proxy import get_pipe_callback
from web.istex_proxy import (
    get_file_from_url,
    get_file_from_id,
    json_to_hits,
    IstexDoctype,
    ark_to_istex_url,
)
from ..errors import IstexError, WebError, FilePathError

from dataclasses import dataclass
from datetime import datetime, timezone
from typing import Optional
from flask import jsonify

from ..subset_tools import get_unzip_callback, ISTEX_ZIP_PATTERN, Subset


@dataclass
class StatusResponse:
    """Handles status response formatting for API requests"""

    VALID_STATUSES = {"queued", "started", "finished", "failed"}

    status: str
    http_code: int = 200
    paper: Optional['Paper'] = None
    paper_id: Optional[int] = None
    ppl_ver: Optional[str] = None
    task_status: Optional[str] = None
    cat_is_processed: Optional[bool] = False
    message: str = ""
    alt_message: str = ""
    task_started: datetime = ""
    task_stopped: datetime = ""

    def __post_init__(self):
        if self.status not in ["success", "failed"]:
            raise ValueError(f"response status must be failed or success, not {self.status}")

        if not (self.paper or self.paper_id):
            raise ValueError("paper_id must be provided if paper is None")

        # set fields from paper if not set by constructor
        if self.paper is not None:
            self.paper_id = self.paper_id or self.paper.id
            self.ppl_ver = self.ppl_ver or self.paper.pipeline_version
            self.task_status = self.task_status or self.paper.task_status
            self.task_started = self.paper.task_started
            self.task_stopped = self.paper.task_stopped
            self.cat_is_processed = self.paper.has_cat and self.paper.cat_in_db

        if isinstance(self.task_started, datetime):
            self.task_started = self.task_started.replace(tzinfo=timezone.utc).astimezone(ZoneInfo("Europe/Paris"))
        if isinstance(self.task_stopped, datetime):
            self.task_stopped = self.task_stopped.replace(tzinfo=timezone.utc).astimezone(ZoneInfo("Europe/Paris"))

    def _format_task_status(self) -> str:
        return self.task_status if self.task_status in self.VALID_STATUSES else "undefined"

    def _calculate_elapsed_time(self) -> str:
        if not isinstance(self.task_started, datetime):
            return ""

        _current_time = datetime.now(ZoneInfo("Europe/Paris"))
        if self.task_status in ["started", "queued"]:
            elapsed = _current_time - self.task_started

        elif self.task_status in ["finished", "failed"] and isinstance(self.task_stopped, datetime):
            elapsed = self.task_stopped - self.task_started
        else:
            return ""

        return str(elapsed).split(".")[0]

    def _format_message(self) -> str:
        if self.message:
            return self.message

        if self._format_task_status() == "undefined":
            return "No job run yet"

        return f"{self.task_status:9} {self._calculate_elapsed_time()}"

    def _format_alt_message(self) -> str:
        if self.alt_message:
            return self.alt_message

        started_str = self.task_started.strftime('%Y-%m-%dT%H:%M:%S') if self.task_started else "(no time info)"

        if self.task_status in ["started", "finished", "failed"]:
            return f"Started {started_str}"
        elif self.task_status == "queued":
            return f"Waiting since {started_str}"

        return ""

    @property
    def response(self):
        data = {
            "paper_id": self.paper_id,
            "ppl_ver": self.ppl_ver,
            "task_status": self._format_task_status(),
            "task_started": self.task_started,
            "task_stopped": self.task_stopped,
            "cat_is_processed": self.cat_is_processed,
            "message": self._format_message(),
            "alt_message": self._format_alt_message()
        }
        return jsonify({"status": self.status, "data": data}), self.http_code


def allowed_file(filename):
    # TODO: REFACTOR use models.FileType instead
    return (
            "." in filename
            and filename.rsplit(".", 1)[1].lower()
            in current_app.config["ALLOWED_EXTENSIONS"]
    )


# TODO: REFACTOR please move function to models.paper.method
def get_paper_file(paper_id, file_type):
    """
    Return the filepath for the given paper as id

    @param paper_id:  id of the paper
    @param file_type:  type of the wanted file (@see FileType)
    @return:
    """

    paper = db.session.get(Paper, paper_id)
    if paper is None:
        flash(f"No such paper {paper_id}")
        return None

    # TODO: REWRITE
    # check filetype
    if isinstance(file_type, str):
        # convert to enum
        try:
            file_type = getattr(BhtFileType, file_type.upper())
        except AttributeError:
            flash(f"Wrong file type {file_type}")
            return None
    elif not isinstance(file_type, BhtFileType):
        flash(f"Wrong file type {file_type}")
        return None

    # TODO: REWRITE
    if file_type == BhtFileType.PDF and paper.has_pdf:
        file_path = paper.pdf_path
    elif file_type == BhtFileType.CAT and paper.has_cat:
        file_path = paper.cat_path
    elif file_type == BhtFileType.TXT and paper.has_txt:
        file_path = paper.txt_path
    else:
        flash(f"No {file_type} file for paper {paper_id}")
        return None

    if not os.path.isabs(file_path):
        file_path = os.path.join(current_app.config["WEB_UPLOAD_DIR"], file_path)

    if not os.path.isfile(file_path):
        flash(f"No {file_type} file for paper {paper_id}")
        return None

    return file_path


#  - - - - - - - - - - - - - - - - - - A P P  C O N F I G U R A T I O N S - - - - - - - - - - - - - - - - - - - - #

@bp.app_template_filter("short_timedelta")
def short_timedelta(in_timedelta):
    # out_timedelta = ""
    # if type(in_timedelta) is np.timedelta64:
    #     out_timedelta = in_timedelta.astype(str)[:-6]
    # elif type(in_timedelta) is datetime.timedelta:
    #     out_timedelta = datetime.timedelta(
    #         days=in_timedelta.days,
    #         seconds=in_timedelta.seconds,
    #         microseconds=0,
    #     )
    out_timedelta = type(in_timedelta)

    return out_timedelta


@bp.app_template_filter("short_datetime")
def short_datetime(date_time):
    if type(date_time) is str:
        date = parser.parse(date_time)
        native = date.replace(tzinfo=None)
    else:
        native = date_time
    new_datetime = native.strftime("%Y-%m-%dT%H:%M:%S")
    return new_datetime


@bp.app_template_filter("staticversion")
def staticversion_filter(filename):
    newfilename = "{0}?v={1}".format(filename, current_app.config["VERSION"])
    return newfilename


@bp.app_template_filter("basename")
def basename_filter(filename):
    if not filename:
        return None
    return os.path.basename(filename)


# Add colors as default variable for all templates
@bp.before_request
def add_css_colors_to_templates():
    # Insert CSS_COLORS in template's global context
    current_app.jinja_env.globals['css_colors'] = current_app.config['CSS_COLORS']


first_request = True


@bp.before_request
def initialize_data():
    global first_request
    if first_request:
        # DO WHATEVER AT FIRST REQUEST
        first_request = False


#  - - - - - - - - - - - - - - - - - - - - U T I L S - - - - - - - - - - - - - - - - - - - - - - - - #
def db_stats():
    all_events = HpEvent.query.all()
    processed_papers = Paper.query.filter_by(cat_in_db=True).all()
    all_missions = Mission.query.all()
    if len(all_events) > 1:
        events_start_dates_asc = sorted(
            [_e.start_date for _e in all_events], reverse=False
        )
        events_stop_dates_dsc = sorted(
            [_e.stop_date for _e in all_events], reverse=True
        )
        global_start = events_start_dates_asc[0].strftime("%Y-%m-%d")
        global_stop = events_stop_dates_dsc[0].strftime("%Y-%m-%d")
    else:
        global_start = ""
        global_stop = ""

    _db_stats = {
        "num_events": len(all_events),
        "num_papers": len(processed_papers),
        "num_missions": len(all_missions),
        "global_start": global_start,
        "global_stop": global_stop,
    }

    return _db_stats


#  - - - - - - - - - - - - - - - - - - - - R O U T E S - - - - - - - - - - - - - - - - - - - - - - - - #

@bp.errorhandler(Exception)
def handle_exception(e):
    current_app.logger.exception(f"Exception has occurred: {e}")
    return "FLASK Internal Error", 500


@bp.route("/")
def index():
    # return render_template("index.html")
    return redirect(url_for("main.catalogs"))


@bp.route("/favicon.ico")
def favicon():
    return send_from_directory(
        os.path.join(current_app.static_folder, "img"),
        "bht2-32x32.png",
        mimetype="image/vnd.microsoft.icon",
    )


@bp.route("/changelog/<module>")
@bp.route("/changelog", defaults={"module": "main"})
def changelog(module):
    import markdown

    if module == "main":
        changelog_path = os.path.join(
            current_app.config["BHT_ROOT_DIR"], "CHANGELOG.md"

web/main/templates/_db_stats.html
<blockquote class="text-center">
    {% if paper %}
    <p class="lead fs-4 mb-0">
        {{events | length }} Events for the paper
        <a class="btn btn-warning paper-id" href="{{url_for('main.paper_show', paper_id=paper.id)}}"
           title="Show paper #{{paper.id}}">
            {{paper.id}}
        </a>
        with pipeline
        <a class="btn btn-warning btn-version" href="{{url_for('main.changelog', module='pipeline')}}"
           title="Please see CHANGELOG for changes">
            V{{paper.pipeline_version}}
        </a>
    </p>
    <p class="fs-4 mb-0 fw-bolder">
        "{{paper.title}}
    </p>
    {% elif db_stats.num_events > 0 %}
    <blockquote class="text-center">
        <p class="lead fs-4 mb-0">
            {{db_stats.num_papers}} Papers processed to find
        </p>
        <p class="lead fs-4 mb-0">
            {{db_stats.num_events}} Events across {{db_stats.num_missions}} Missions
        </p>
        <p class="lead fs-4 mb-0">
            from {{db_stats.global_start}} to {{db_stats.global_stop}}
        </p>
    </blockquote>
    {% else %}
    <p class="lead fs-4 mb-0">
        <span class="fw-bold">{{events | length }}</span> Events in whole database
    </p>
    {% endif %}
</blockquote>

web/main/templates/_papers_pagination.html
{% if papers.pages > 1 %}
{% if insert == 'top' %}
    Page {{ papers.page }} / {{ papers.pages }} ({{ papers.total }} total papers)
{% elif insert == 'bottom' %}
    <hr class="mt-2 mb-3">
{% endif %}

<div class="pagination_menu">
    {% if papers.has_prev %}
    <a class="btn btn-warning" href="{{ url_for(url_value, page=papers.prev_num, requested_status=requested_status) }}"
       title="Previous {{config.PER_PAGE}} Papers"><<</a>
    {% endif %}
    &nbsp;
    {% if papers.has_next %}
    <a class="btn btn-warning" href="{{ url_for(url_value, page=papers.next_num, requested_status=requested_status) }}"
       title="Next {{config.PER_PAGE}} Papers">>></a>
    {% endif %}
</div>
{% if insert == 'top' %}
    <hr class="mt-2 mb-3">
{% elif insert == 'bottom' %}
    Page {{ papers.page }} / {{ papers.pages }} ({{ papers.total }} total papers)
{% endif %}
{% endif %}

web/main/templates/about.html
{% extends "base_page.html" %}
{%  block more_head %}
<title>About - {{base_title}}</title>
{%  endblock %}

{% block content %}
<div class="container">
    <p>
        BibHelioTech aims at identifying temporal expressions (time intervals) in scientific papers from the
        Heliophysics domain and linking them to their observational context: satellites, instruments, spatial regions.
        It connects to <a href="https://www.istex.fr/">Istex</a>, a large database of papers authorized to text and data
        mining.
    </p>

    <p>
        BibHelioTech generates standardized catalogues of events which may be visualized in data analysis tools, such as
        <a href="http://amda.cdpp.eu/">AMDA</a> or <a href="https://github.com/SciQLop/SciQLop">Sciqlop.</a>
    </p>

    <p>
        BibHelioTech was developed at <a href="https://www.irap.omp.eu/">IRAP</a> (Institut de Recherche en
        Astrophysique et Planétologie, Toulouse
        ) in the frame of an internship by A. Dablanc supervised by V. Génot.
    </p>
    <p>
        This web interface
        is developed by <a href="mailto:hitier.richard@gmail.com">R. Hitier</a>.
    </p>
    <p>
        BibHelioTech repository is available on
        <a href="https://github.com/RichardHitier/BibHelioTech">
            <img width="70" src="{{url_for('static', filename='img/GitHub_Logo.png')}}"/>
        </a>
    </p>
    <h5>
        See Changelogs for more details on changes between versions:
    </h5>
    <ul>
        <li>
            BibHelioTech: <a class="btn btn-version" href="{{url_for('main.changelog')}}"
                             title="BibHelioTech CHANGELOG">
            V{{config.VERSION}}</a>

        </li>
        <li>
            BhtPipeline: <a class="btn btn-version" href="{{url_for('main.changelog', module='pipeline')}}"
                            title="BhtPipeline CHANGELOG">
            V{{config.BHT_PIPELINE_VERSION}}</a>

        </li>

    </ul>
    <h5>
        Pipeline Hints:
    </h5>
    <ul>
        <li> First, SUTIME is run to discover time intervals called Durations.</li>
        <li> Then we search for Missions and Instruments in the text.</li>
        <li> A correspondance is then done between Missions and Durations</li>
        <li> That allows us to set some indicators:
            <ul>
                <li>D: is the distance in the text ( number of characters) between the Duration and the Mission</li>
                <li>R: is the rank of the mission, meaning how many missions we had to skip in the text before making
                    the correspondance with the Duration
                </li>
                <li>Conf: is an indice, which formula is:
                    <strong>D × R / (SO × sat_occ)</strong> where <strong>SO</strong> is the total number of missions,
                    and <strong>sat_occ</strong> the occurrences of that specific mission.
                </li>
                <li>NConf: is this indice normalized on the whole database</li>
            </ul>
        </li>
    </ul>

</div>
{% endblock %}

web/main/templates/admin.html
{% extends "base_table.html" %}
{% block more_head %}
{{ super () }}
<title> {{papers.total }} Catalogs pending - {{base_title}}</title>
{%  endblock %}
{% block content %}
{#
Show a list of catalogs files not already inserted in db
--------------------------------------------------------
#}
{% if not papers.items|length == 0 %}
<h4>{{papers.total }} Catalogs to add in database:</h4>
{% with url_value = 'main.admin' , insert='top'%}
{% include '_papers_pagination.html' %}
{% endwith %}
<table class="table-hover table">
    {% for paper in papers %}
    <tr>
        <th scope="row" class="td_num">
            <a class="btn btn-warning paper-id" href="{{url_for('main.paper_show', paper_id=paper.id)}}"
               title="Show paper #{{paper.id}}">
                {{paper.id}}
            </a>
        </th>
        <td class="col-4 text-truncate" style="max-width: 550px;" title="{{paper.ark}}">
            {{paper.title}}
        </td>
        <td class="col-6">
            <button class="btn btn-warning add-catalog position-relative" data-paper_id="{{paper.id}}"
             {% if not paper.has_cat %}disabled{% endif %}>
                add in db
                <span class="position-absolute top-0 start-100 translate-middle p-1 bg-danger border border-light rounded-circle">
                </span>
            </button>
        </td>
    </tr>
    {% endfor %}
</table>
{% endif %}
{% with url_value = 'main.admin', insert='bottom' %}
    {% include '_papers_pagination.html' %}
{% endwith %}
{%  endblock content %}

{% block scripts %}
{{ super() }}
<script src="{{url_for('static', filename='js/tools.js') | staticversion }} "></script>
<script>
    $(document).ready(function() {

        // For each un-added catalog button, attach callback:
        $('.add-catalog').on('click', push_catalog );

    });
</script>
{%  endblock %}

web/main/templates/catalogs.html
{% extends "base_table.html" %}
{% block more_head %}
{{ super () }}
<title> {{events | length}} Events to display - {{base_title}}</title>
{% endblock %}
{% block content %}
<div id="download-modal" class="modal fade" tabindex="-1"   role="dialog">
  <div class="modal-dialog" role="document">
    <div class="modal-content">
      <div class="modal-header">
        <h5 class="modal-title">Catalog Ready</h5>
        <button type="button" class="close" data-bs-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body text-center">
          <div id="modal-spinner" class="text-center spinner-border text-warning" role="status">
              <span class="visually-hidden">Loading...</span>
          </div>
          <p id="modal-body"></p>
      </div>
      <div class="modal-footer">
        <a type="button" class="btn btn-warning" id="download-catalog" >Download</a>
        <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>
{% if db_stats.filtered_events > 0 %}
<blockquote class="text-center">
    <p class="lead fs-4 mb-0">
        <span class="number-bold">{{db_stats.filtered_events}}</span> Events filtered over a total <span
            class="number-bold">{{db_stats.total_events}}</span>
    </p>
    <p class="lead fs-4 mb-0">
        for missions: <span class="number-bold">{{db_stats.selected_missions|join(', ')}}</span>
    </p>
    <p class="lead fs-4 mb-0">
        with filters MinDuration: <span class="number-bold">{{params.duration_min}} min</span>, MaxDuration: <span
            class="number-bold">{{params.duration_max}} min</span>, MinNConf: <span class="number-bold">{{params.nconf_min}}</span>
    </p>
</blockquote>
<hr class="mt-2 mb-3">
{% endif %}
{#
Show missions found in db as clickable buttons, triggering mission's events display
-----------------------------------------------------------------------------------
#}
<form id="catalog-filter" action="{{url_for('main.catalogs')}}" method="post">
    <div class="row">
        <div class="col">
            <h4 class="mb-3 d-inline-block">Filters:</h4>
        </div>
        <div class="col">
            <div class="form-group">
                <label for="duration-min">Min duration: <span class="duration-val"></span></label>
                <input class="form-control filter-input" id="duration-min" name="duration-min" type="number"
                       value="{{params.duration_min}}"/>
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label for="duration-max">Max duration: <span class="duration-val"></span></label>
                <input class="form-control filter-input" id="duration-max" name="duration-max" type="number"
                       value="{{params.duration_max}}"/>
            </div>
        </div>
        <div class="col">
            <div class="form-group">
                <label for="nconf-min">Min NConf (0.0 - 1.0)</label>
                <input class="form-control filter-input" id="nconf-min" name="nconf-min" type="number"
                       value="{{params.nconf_min}}"
                       placeholder="1.0" step="0.0000001" min="0.0" max="1.0"/>
            </div>
        </div>
    </div>
    <hr class="mt-3 mb-3">
    <div id="missions-menu" class="mb-4 mt-4 d-flex justify-content-between align-items-center">
        <h4 >Available Missions :</h4>
        <div>
            <input class='btn btn-warning' id="show-events-btn" type="submit" value="Show Events" disabled/>
            <button id="make-catalog"
                    class='btn btn-warning'
                    title="Download as as HPevents catalog">
                Make Catalog
            </button>
        </div>
        <div class="btn-group">
            <button id="missions-alpha-asc" class="btn-sort" title="Sort mission by asc alphabetical order"> Alpha &UpTeeArrow; </button>
            <button id="missions-alpha-dsc" class="btn-sort" title="Sort mission by desc alphabetical order"> Alpha &DownTeeArrow; </button>
            <button id="missions-num-asc" class="btn-sort" title="Sort mission by asc numerical order"> Num &UpTeeArrow; </button>
            <button id="missions-num-dsc" class="btn-sort" title="Sort mission by desc numerical order"> Num &DownTeeArrow; </button>
        </div>
    </div>
    <div class="row" id="catalogs-row">
        {% for mission in missions %}
            {% if mission.id in params.selected_missions %}
                {%set checked = "checked"%}
            {% else %}
                {%set checked = ""%}
            {% endif %}
            <div class="col-2">
                <label class="btn mission-catalog" title="Show {{mission.num_events}} events for mission {{mission.name}}">
                    <input name="missions" type="checkbox" {{ checked }} class="filter-input form-check-input"
                           value="{{mission.id}}">
                    {{mission.name}}
                    <span class="badge bg-light border text-dark">{{mission.num_events}}</span>
                </label>
            </div>
        {% endfor %}
    </div>

</form>
<hr class="mt-2 mb-3">
{#
Show found events after form submit
-----------------------------------
#}
{% include 'events-table.html' %}

{%  endblock %}

{% block scripts %}
{{ super() }}
<script>
    function format_minutes(minutes) {
        const day = Math.floor(minutes / (24 * 60));
        const hour = Math.floor((minutes % (24 * 60)) / 60);
        const minute = minutes % 60;

        let result = "";
        if (day > 0) {
            result += `${day}d `;
        }
        if (hour > 0 || day > 0) {
            result += `${hour}h `;
        }
        result += `${minute}m`;

        return result.trim();
    }

    function enable_submit() {

        if( $('#show-events-btn').hasClass( "to-submit")){
           return;
        }
        $('#show-events-btn').prop('disabled', false);
        $('#show-events-btn').addClass('to-submit', 500);
        $('#show-events-btn').toggle( "fade");
        $('#show-events-btn').toggle( "fade");
        $('#make-catalog').attr('disabled', 'disabled');
    }

    function update_duration_span(duration_input){
            var duration_str = format_minutes(duration_input.val());
            duration_input.siblings("label").children("span").html(duration_str);
    }


    function sort_num(asc) {
        let $container = $("#catalogs-row");

        let $items = $container.children(".col-2").get(); // Récupère une liste JS

        $items.sort(function (a, b) {
            let numA = parseInt($(a).find(".badge").text().trim(), 10) || 0;
            let numB = parseInt($(b).find(".badge").text().trim(), 10) || 0;
            return asc ? numA - numB : numB - numA;
        });

        $container.append($items); // Réinsère les éléments triés dans le bon ordre
    }


    function sort_alpha(asc) {
        let $container = $("#catalogs-row");
        let $items = $container.children(".col-2").get();

        $items.sort(function (a, b) {
            let textA = $(a).find("label").contents().filter(function () {
                return this.nodeType === 3; // Sélectionne uniquement les nœuds de texte
            }).text().trim();

            let textB = $(b).find("label").contents().filter(function () {
                return this.nodeType === 3; // Sélectionne uniquement les nœuds de texte
            }).text().trim();

            if (textA < textB) {
                return asc ? -1 : 1;
            }
            if (textA > textB) {
                return asc ? 1 : -1;
            }
            return 0;
        });

        $container.append($items);
    }


    $(document).ready(function() {
        function handleSortClick(event, sortFunction, ascending) {
            event.preventDefault(); // prevents page reloading for any sort btn
            $('.btn-sort').removeClass('active');
            $(this).addClass('active', 500);
            sortFunction(ascending);
        }


        // For any 'missions sort' button, set the sorting on click

        $('#missions-num-asc').on('click', function (event) {
            handleSortClick.call(this, event, sort_num, true);
        });

        $('#missions-num-dsc').on('click', function (event) {
            handleSortClick.call(this, event, sort_num, false);
        });

        $('#missions-alpha-asc').on('click', function (event) {
            handleSortClick.call(this, event, sort_alpha, true);
        });

        $('#missions-alpha-dsc').on('click', function (event) {
            handleSortClick.call(this, event, sort_alpha, false);
        });

        // at last, simulate click on one button
        $('#missions-num-asc').click();



        // Any duration input span label should be updated at start
        $('input.filter-input[type="number"]').each( function(){
            update_duration_span($(this));
        });

        // Bind input key to duration span update and submit btn blink
        $('input.filter-input[type="number"]').on("input", function(){
            update_duration_span($(this));
            enable_submit();
        });

        // Any check event should turn show 'events button' to color
        $('.filter-input[type=checkbox]').change( enable_submit);

        const dl_modal = new bootstrap.Modal('#download-modal');

        // Now Deal with the 'make catalog' button:
        // 1- request for the catalog url with parameters as POST
        // 2- open a modal dialog window with a link to download file
        //
        $('#make-catalog').on('click',  function (event) {
            // build a selected mission name list
            const selected_mission_names = "{{db_stats.selected_missions|join(', ')}}";
            event.preventDefault();
            let params = {};
            params["events-ids"] = {{events_ids}};
            fetch_url = '{{url_for('main.api_catalogs_txt')}}';
            $('.modal-title').html("Catalog Building ... ");
            $("#download-catalog").attr('disabled', 'disabled');
            $('#modal-spinner').show();
            $('#modal-body').hide();
            dl_modal.show();
            fetch(fetch_url, {
                "method": "POST",
                "headers": {"Content-Type": "application/json"},
                "body": JSON.stringify(params),
            })
            .then( res  => {
                //console.log(res.headers);
                // Extract filename from response headers
                const header = res.headers.get('Content-Disposition');
                const parts = header.split(';');
                filename = parts[1].split('=')[1].replaceAll("\"", "");
                return res.blob() ;
            })
            .then(blob => {
                // Get the download url from response's blob, insert in modal window
                var url = window.URL.createObjectURL(blob);
                var a = $('#download-catalog');
                a.attr('href', url);
                a.attr('download' , filename);
                a.removeAttr('disabled');

                $('.modal-title').html("Catalog Ready");
                $('#modal-body').html("Missions:<br><br>"+selected_mission_names);
                $('#modal-spinner').hide();
                $('#modal-body').show();
            });
       }); // end click on #make-catalog

       // Close modal window after downloading file
       $('#download-catalog').on('click', function(){
          dl_modal.hide();
       });

        // Sortable table
        //new DataTable('#events-table', {
        //    ordering: true,
        //    search: true,
        //    paging: false,
        //    buttons: [
        //        'csv'
        //    ],
        //    layout: {
        //        topStart: 'buttons'
        //    },
        //});

    });



</script>
{%  endblock %}

web/main/templates/configuration.html
{% extends "base_page.html" %}
{%  block more_head %}
{%  endblock %}

{% block content %}
<h1>This is configuration:</h1>
<table>
    {% for k, v in configuration.items()%}
    <tr>
        <td>{{k}}</td>
        <td>{{v}}</td>
    </tr>
    {%endfor%}
</table>

{%  endblock %}

web/main/templates/events.html
{% extends "base_table.html" %}
{% block more_head %}
{{ super () }}
{% if paper %}
<title>{{events | length}} Events for paper {{paper.id}}</title>
{% else %}
<title>{{events | length}} Events in database</title>
{% endif %}
{% endblock %}
{% block content %}
{% include '_db_stats.html' %}
<hr class="mt-2 mb-3">
{% include 'events-table.html' %}

{%  endblock %}
{% block scripts %}
{{ super() }}
<script>
    /*
    $(document).ready(function() {
        new DataTable('#events-table', {
            ordering: true,
            search: true,
            paging: true,
            pageLength: 100,
            buttons: [
                'csv'
            ],
            layout: {
                topStart: 'buttons'
            },
        });
    });
    */
</script>
{%  endblock %}